<?php

/**
 * @file
 * Contains learn_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function learn_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the learn_migration module.
    case 'help.page.learn_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom class and controller for migration') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function learn_migration_preprocess_page(&$variables) {
  if (\Drupal::currentUser()->hasPermission('access toolbar')) {
    $variables['#attached']['library'][] = 'learn_migration/migration_icon';
  }
}